version: '3'

services:
  php:
    #image: php:8.1-fpm
    build:
      context: ./docker/php
    volumes:
      - './blogmvc:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './blogmvc:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - "mysql"
    links:
      - "mysql"
    ports:
      - 8081:80
    environment:
      #- MYSQL_USER=root
      #- MYSQL_PASSWORD=root
      #- MYSQL_ROOT_PASSWORD=root
      - PMA_ARBITRARY=1
